## Import NumPy

In [1]:
import numpy as np

## Create NumPy arrays

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.arange(1, 11)
matrix = np.array([[1, 2, 3], [4, 5, 6]])

## Indexing & slicing

In [3]:
print(arr1[2])        # single element
print(arr2[2:7])     # slicing
print(matrix[0, 1])  # matrix access

30
[3 4 5 6 7]
2


## Mathematical operations

In [4]:
print(arr1 + 5)
print(arr1 * 2)
print(np.sqrt(arr1))

[15 25 35 45 55]
[ 20  40  60  80 100]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


## Statistical operations

In [5]:
print(np.mean(arr1))
print(np.median(arr1))
print(np.max(arr1))
print(np.min(arr1))

30.0
30.0
50
10


## Axis-wise operations

In [6]:
print(np.sum(matrix, axis=0))  # column-wise
print(np.sum(matrix, axis=1))  # row-wise

[5 7 9]
[ 6 15]


## Reshaping & broadcasting

In [7]:
reshaped = arr2.reshape(2, 5)
print(reshaped)

broadcasted = reshaped + 10
print(broadcasted)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


## Save & load NumPy array

In [10]:
np.save("data.npy", arr1)
loaded = np.load("data.npy")
print(loaded)

[10 20 30 40 50]


## NumPy vs Python list performance

In [9]:
import time

python_list = list(range(1000000))
np_array = np.arange(1000000)

start = time.time()
[x * 2 for x in python_list]
print("Python list time:", time.time() - start)

start = time.time()
np_array * 2
print("NumPy time:", time.time() - start)

Python list time: 0.31858348846435547
NumPy time: 0.005475521087646484
